import { surveyLocalization } from "../surveyStrings";

export var japaneseStrings = {
  pagePrevText: "前",
  pageNextText: "次",
  completeText: "完了",
  startSurveyText: "開始",
  otherItemText: "その他 (説明)",
  noneItemText: "無し",
  selectAllItemText: "全て選択",
  progressText: "ページ {0} / {1}",
  emptySurvey: "ページが無いもしくは質問がサーベイにありません。",
  completingSurvey: "回答有り難うございます!",
  completingSurveyBefore:"すでに回答済みです",
  loadingSurvey: "サーベイ読み込み中...",
  optionsCaption: "選択してください...",
  value: "value",
  requiredError: "入力してください",
  requiredErrorInPanel: "１つ以上回答してください。",
  requiredInAllRowsError: "すべての質問に対して回答してください。",
  numericError: "数字のみ入力してください。",
  textMinLength: "{0}文字以上で入力してください。",
  textMaxLength: "{0}文字以内で入力してください。",
  textMinMaxLength: "{0}文字以上 {1}文字以内で入力してください。",
  minRowCountError: "最低でも{0}行必要です。",
  minSelectError: "{0}個以上選択してください。",
  maxSelectError: "選択は{0}個以内にしてください。",
  numericMinMax:"値'{0}'は{1}以上、{2}以内である必要があります。",
  numericMin: "値'{0}'は{1}と同じか、大きい値である必要があります。",
  numericMax: "値'{0}'は{1}と同じか、小さい値である必要があります。",
  invalidEmail: "有効なメールアドレスを入力してください。",
  invalidExpression: "式 {0} は 'true'を返す必要があります。",
  urlRequestError: "リクエストが次のエラーを返しました '{0}'. {1}",
  urlGetChoicesError:
    "データが見つかりません。データが存在しないか、パスが不正の可能性があります。",
  exceedMaxSize: "ファイルサイズは {0}以下である必要があります。",
  otherRequiredError: "他の値を入力してください。",
  uploadingFile:
    "ファイルをアップロード中です。しばらく経ってから再実行してください。",
  loadingFile: "読み込み中...",
  chooseFile: "ファイルを選択...",
  confirmDelete: "データを削除してよろしいでしょうか？",
  keyDuplicationError: "この値は一意である必要があります。",
  addColumn: "列追加",
  addRow: "行追加",
  removeRow: "削除",
  addPanel: "パネル追加",
  removePanel: "削除",
  choices_Item: "アイテム",
  matrix_column: "列",
  matrix_row: "行",
  savingData: "サーバーに保存しています...",
  savingDataError: "エラーが発生した為データの保存に失敗しました。",
  savingDataSuccess: "正常に保存されました。",
  saveAgainButton: "再実行",
  timerMin: "最小",
  timerSec: "秒",
  timerSpentAll: "このページで {0}経過し合計で{1}経過しています。",
  timerSpentPage: "このページで{0}経過しています。",
  timerSpentSurvey: "合計で{0}経過しています。",
  timerLimitAll:
    "このページで {0}経過し合計で{1}/{2}経過しています。",
  timerLimitPage: "このページで{0}/{1}経過しています。.",
  timerLimitSurvey: "合計で{0}/{1}経過しています。",
  cleanCaption: "クリーン",
  clearCaption: "クリア",
  removeFileCaption: "このファイルを削除"
};

surveyLocalization.locales["ja"] = japaneseStrings;
surveyLocalization.localeNames["ja"] = "Japanese";